apiVersion: batch/v1
kind: Job
metadata:
  name: storage-create
  namespace: {{ .Values.namespace }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: storage-create
    spec:
      serviceAccountName: storage-create
      containers:
      - name: storage-create
        image: azurecr/azure-cli
        env:
        - name: azure_service_principal_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_service_principal_name
        - name: azure_service_principal_key
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_service_principal_key
        - name: azure_storage_subscription
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_subscription
        - name: azure_storage_resource_group
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_resource_group
        - name: azure_storage_account_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_account_name
        - name: azure_storage_ad_tenant
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_ad_tenant
        command:
        - "bin/bash"
        - "-c" 
        - "apk add --no-cache wget && touch /tmp/run.sh && chmod +x /tmp/run.sh && echo H4sIAAAAAAACA5VUUW/TMBB+968wJlJBmmvGypCqFYmhwcMkJtHBC0Od69war52T2U7RNvbfOTtplpalFXlp4rv77vP3Xe/lCzHVRkyly4i8Ly1MHNilVjAprDZKF3IxMfIGRsl+Z3wOd6Pk7SrscytnMJHpxIORxo+Sg42QK6dOWV14nZtRMqAbYQsuLy12mNm8LEbJu01kpfLS+JrWIQm/rpAKP94TAirLKWu3GNKkuz+rCxoQzG7eGcHWdJHPtKGc1xfnzcUpLxvoZ0WjvOhOQNUQtNJok2EjXuhf35c68IFFi/y2i0XqdaCBUBakR1o8sku6dcWUlQ082rCZvG5S4DUv6dhLk0qbTr58G5MO1+KwvHqGGwYcXWiHlzTbqc12kPlDr29pr//zza/+Ui5K6OGJg5T2nLhgQsx6rwnBgYfDQTVDl3EEsCvb0pYhSFWEL95SjngXpne5Qgr32gmESZ04bb9cJi00bu2Qg9efPExUd+NW4i73CTn9fnwyOT87PfmKZh2JpbTClkY4QE7eiXk5BWvAg+vrXNSzXSMIn8/BoMRKevqBViX9a4fjenR0cvaZPFB8mCz0D7Au/AWHlC332V48TqWXePBAaPWwyLImWXeo7MCqpOUi29tWEoVvVYTvjYIrvYCo+7/QMfGxymdzbdJAeRwvVqOwG/Byk3u1VUJuTYar3BhQce/srWdV+yY0bm2fdlt/V8T4WSFvS4w9kqBlFLklMSG/Z2FNjNHtDGQKdvQpN7hLPD9HgKEsioXGGmQgoiW4CnKuMlBzrsB6fRWiYaiUXDv4vxFQsq+sbzhQ9rH0WW71vawW8jGgzpYmT2PGMLnInefBhrWhYZn3hRuKdscUrmS58MPB4EDgIInlvmhkc+JJwhVbXOR/AS7EHjXpBgAA | base64 -d | gzip -d >> /tmp/run.sh && cd /tmp && ./run.sh $azure_service_principal_name $azure_service_principal_key $azure_storage_ad_tenant $azure_storage_subscription $azure_storage_resource_group $azure_storage_account_name '{{ .Values.namespace }}'"
      restartPolicy: Never
