apiVersion: v1
kind: Secret
metadata:
  name: storage-create
type: Opaque
data:
  azure_service_principal_name: {{ index .Values "storage-create" "azure_service_principal_name" | b64enc }}
  azure_service_principal_key: {{ index .Values "storage-create" "azure_service_principal_key" | b64enc }}
  azure_storage_ad_tenant: {{ index .Values "storage-create" "azure_storage_ad_tenant" | b64enc }}
  azure_storage_subscription: {{ index .Values "storage-create" "azure_storage_subscription" | b64enc }}
  azure_storage_resource_group: {{ index .Values "storage-create" "azure_storage_resource_group" | b64enc }}
  azure_storage_account_name: {{ index .Values "storage-create" "azure_storage_account_name" | b64enc }}
